name: Package

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/mygento/deployer:v3
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
        - name: Check Composer
          run: composer -V
        - name: Check Version
          run: sh check-version.sh
        - name: Download and Build
          run: sh postman-deb.sh
        - name: Results
          run: ls -lah .
        - name: Upload
          run: which upload_package
        - name: Upload
          run: sh upload.sh
          env:
            SERVICE: ${{ secrets.SERVICE }}
            REALM: ${{ secrets.REALM }}
            REALM_LOGIN: ${{ secrets.REALM_LOGIN }}
            REALM_PASS: ${{ secrets.REALM_PASS }}
